// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// source: engine.proto

package engine

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

const _ = grpc.SupportPackageIsVersion7

// EngineClient is the client API for Engine service.
type EngineClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (Engine_ConnectClient, error)
}

type engineClient struct {
	cc grpc.ClientConnInterface
}

func NewEngineClient(cc grpc.ClientConnInterface) EngineClient {
	return &engineClient{cc}
}

func (c *engineClient) Connect(ctx context.Context, opts ...grpc.CallOption) (Engine_ConnectClient, error) {
	stream, err := c.cc.NewStream(ctx, &Engine_ServiceDesc.Streams[0], "/engine.Engine/Connect", opts...)
	if err != nil {
		return nil, err
	}
	x := &engineConnectClient{stream}
	return x, nil
}

type Engine_ConnectClient interface {
	Send(*EngineCommand) error
	Recv() (*EngineEvent, error)
	grpc.ClientStream
}

type engineConnectClient struct {
	grpc.ClientStream
}

func (x *engineConnectClient) Send(m *EngineCommand) error {
	return x.ClientStream.SendMsg(m)
}

func (x *engineConnectClient) Recv() (*EngineEvent, error) {
	m := new(EngineEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// EngineServer is the server API for Engine service.
type EngineServer interface {
	Connect(Engine_ConnectServer) error
}

// UnimplementedEngineServer should be embedded to have forward compatible implementations.
type UnimplementedEngineServer struct {
}

func (UnimplementedEngineServer) Connect(Engine_ConnectServer) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}

// UnsafeEngineServer may be embedded to opt out of forward compatibility for this service.
type UnsafeEngineServer interface {
	mustEmbedUnimplementedEngineServer()
}

func RegisterEngineServer(s grpc.ServiceRegistrar, srv EngineServer) {
	s.RegisterService(&Engine_ServiceDesc, srv)
}

func _Engine_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EngineServer).Connect(&engineConnectServer{stream})
}

type Engine_ConnectServer interface {
	Send(*EngineEvent) error
	Recv() (*EngineCommand, error)
	grpc.ServerStream
}

type engineConnectServer struct {
	grpc.ServerStream
}

func (x *engineConnectServer) Send(m *EngineEvent) error {
	return x.ServerStream.SendMsg(m)
}

func (x *engineConnectServer) Recv() (*EngineCommand, error) {
	m := new(EngineCommand)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Engine_ServiceDesc is the grpc.ServiceDesc for Engine service.
var Engine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "engine.Engine",
	HandlerType: (*EngineServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _Engine_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "engine.proto",
}
