// Code generated by protoc-gen-go. DO NOT EDIT.
// source: engine.proto

package engine

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

const _ = proto.ProtoPackageIsVersion3

type ControlCommand_Action int32

const (
	ControlCommand_START           ControlCommand_Action = 0
	ControlCommand_STOP            ControlCommand_Action = 1
	ControlCommand_EMERGENCY_STOP  ControlCommand_Action = 2
	ControlCommand_RESET_EMERGENCY ControlCommand_Action = 3
)

var ControlCommand_Action_name = map[int32]string{
	0: "START",
	1: "STOP",
	2: "EMERGENCY_STOP",
	3: "RESET_EMERGENCY",
}

var ControlCommand_Action_value = map[string]int32{
	"START":            0,
	"STOP":             1,
	"EMERGENCY_STOP":   2,
	"RESET_EMERGENCY":  3,
}

func (x ControlCommand_Action) String() string {
	return proto.EnumName(ControlCommand_Action_name, int32(x))
}

func (ControlCommand_Action) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_engine, []int{2, 0}
}

type EngineCommand struct {
	Payload              isEngineCommand_Payload `protobuf_oneof:"payload"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *EngineCommand) Reset()         { *m = EngineCommand{} }
func (m *EngineCommand) String() string { return proto.CompactTextString(m) }
func (*EngineCommand) ProtoMessage()    {}

func (m *EngineCommand) GetPayload() isEngineCommand_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *EngineCommand) GetConfig() *BotConfig {
	if x, ok := m.GetPayload().(*EngineCommand_Config); ok {
		return x.Config
	}
	return nil
}

func (m *EngineCommand) GetControl() *ControlCommand {
	if x, ok := m.GetPayload().(*EngineCommand_Control); ok {
		return x.Control
	}
	return nil
}

type isEngineCommand_Payload interface {
	isEngineCommand_Payload()
}

type EngineCommand_Config struct {
	Config *BotConfig `protobuf:"bytes,1,opt,name=config,proto3,oneof"`
}

type EngineCommand_Control struct {
	Control *ControlCommand `protobuf:"bytes,2,opt,name=control,proto3,oneof"`
}

func (*EngineCommand_Config) isEngineCommand_Payload()  {}
func (*EngineCommand_Control) isEngineCommand_Payload() {}

type ControlCommand struct {
	Action               ControlCommand_Action `protobuf:"varint,1,opt,name=action,proto3,enum=engine.ControlCommand_Action"`
	Reason               string                `protobuf:"bytes,2,opt,name=reason,proto3"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ControlCommand) Reset()         { *m = ControlCommand{} }
func (m *ControlCommand) String() string { return proto.CompactTextString(m) }
func (*ControlCommand) ProtoMessage()    {}

func (m *ControlCommand) GetAction() ControlCommand_Action {
	if m != nil {
		return m.Action
	}
	return ControlCommand_START
}

func (m *ControlCommand) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

type BotConfig struct {
	EnableSolana           bool    `protobuf:"varint,1,opt,name=enable_solana,json=enableSolana,proto3"`
	EnableBsc              bool    `protobuf:"varint,2,opt,name=enable_bsc,json=enableBsc,proto3"`
	MinLiquidityUsd        float64 `protobuf:"fixed64,3,opt,name=min_liquidity_usd,json=minLiquidityUsd,proto3"`
	MaxTokenAgeSeconds     int32   `protobuf:"varint,4,opt,name=max_token_age_seconds,json=maxTokenAgeSeconds,proto3"`
	MinHolders             int32   `protobuf:"varint,5,opt,name=min_holders,json=minHolders,proto3"`
	MaxTop10Pct            float64 `protobuf:"fixed64,6,opt,name=max_top10_pct,json=maxTop10Pct,proto3"`
	MaxRugScore            float64 `protobuf:"fixed64,7,opt,name=max_rug_score,json=maxRugScore,proto3"`
	MinVolumeUsd           float64 `protobuf:"fixed64,8,opt,name=min_volume_usd,json=minVolumeUsd,proto3"`
	BuyAmountSol           float64 `protobuf:"fixed64,9,opt,name=buy_amount_sol,json=buyAmountSol,proto3"`
	BuyAmountBnb           float64 `protobuf:"fixed64,10,opt,name=buy_amount_bnb,json=buyAmountBnb,proto3"`
	SlippagePct            float64 `protobuf:"fixed64,11,opt,name=slippage_pct,json=slippagePct,proto3"`
	JitoTipLamports        int64   `protobuf:"varint,12,opt,name=jito_tip_lamports,json=jitoTipLamports,proto3"`
	Tp1Pct                 float64 `protobuf:"fixed64,13,opt,name=tp1_pct,json=tp1Pct,proto3"`
	Tp1SellPct             float64 `protobuf:"fixed64,14,opt,name=tp1_sell_pct,json=tp1SellPct,proto3"`
	TrailingStopPct        float64 `protobuf:"fixed64,15,opt,name=trailing_stop_pct,json=trailingStopPct,proto3"`
	TimeExitMinutes        int32   `protobuf:"varint,16,opt,name=time_exit_minutes,json=timeExitMinutes,proto3"`
	TimeExitMinProfitPct   float64 `protobuf:"fixed64,17,opt,name=time_exit_min_profit_pct,json=timeExitMinProfitPct,proto3"`
	Enabled                bool    `protobuf:"varint,18,opt,name=enabled,proto3"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *BotConfig) Reset()         { *m = BotConfig{} }
func (m *BotConfig) String() string { return proto.CompactTextString(m) }
func (*BotConfig) ProtoMessage()    {}

func (m *BotConfig) GetEnableSolana() bool { if m != nil { return m.EnableSolana }; return false }
func (m *BotConfig) GetEnableBsc() bool    { if m != nil { return m.EnableBsc }; return false }
func (m *BotConfig) GetMinLiquidityUsd() float64 { if m != nil { return m.MinLiquidityUsd }; return 0 }
func (m *BotConfig) GetMaxTokenAgeSeconds() int32 { if m != nil { return m.MaxTokenAgeSeconds }; return 0 }
func (m *BotConfig) GetMinHolders() int32 { if m != nil { return m.MinHolders }; return 0 }
func (m *BotConfig) GetMaxTop10Pct() float64 { if m != nil { return m.MaxTop10Pct }; return 0 }
func (m *BotConfig) GetMaxRugScore() float64 { if m != nil { return m.MaxRugScore }; return 0 }
func (m *BotConfig) GetMinVolumeUsd() float64 { if m != nil { return m.MinVolumeUsd }; return 0 }
func (m *BotConfig) GetBuyAmountSol() float64 { if m != nil { return m.BuyAmountSol }; return 0 }
func (m *BotConfig) GetBuyAmountBnb() float64 { if m != nil { return m.BuyAmountBnb }; return 0 }
func (m *BotConfig) GetSlippagePct() float64 { if m != nil { return m.SlippagePct }; return 0 }
func (m *BotConfig) GetJitoTipLamports() int64 { if m != nil { return m.JitoTipLamports }; return 0 }
func (m *BotConfig) GetTp1Pct() float64 { if m != nil { return m.Tp1Pct }; return 0 }
func (m *BotConfig) GetTp1SellPct() float64 { if m != nil { return m.Tp1SellPct }; return 0 }
func (m *BotConfig) GetTrailingStopPct() float64 { if m != nil { return m.TrailingStopPct }; return 0 }
func (m *BotConfig) GetTimeExitMinutes() int32 { if m != nil { return m.TimeExitMinutes }; return 0 }
func (m *BotConfig) GetTimeExitMinProfitPct() float64 { if m != nil { return m.TimeExitMinProfitPct }; return 0 }
func (m *BotConfig) GetEnabled() bool { if m != nil { return m.Enabled }; return false }

type EngineEvent struct {
	Payload              isEngineEvent_Payload `protobuf_oneof:"payload"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *EngineEvent) Reset()         { *m = EngineEvent{} }
func (m *EngineEvent) String() string { return proto.CompactTextString(m) }
func (*EngineEvent) ProtoMessage()    {}

func (m *EngineEvent) GetPayload() isEngineEvent_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *EngineEvent) GetTokenDetected() *TokenDetected {
	if x, ok := m.GetPayload().(*EngineEvent_TokenDetected); ok {
		return x.TokenDetected
	}
	return nil
}

func (m *EngineEvent) GetTokenFiltered() *TokenFiltered {
	if x, ok := m.GetPayload().(*EngineEvent_TokenFiltered); ok {
		return x.TokenFiltered
	}
	return nil
}

func (m *EngineEvent) GetBuySignal() *BuySignal {
	if x, ok := m.GetPayload().(*EngineEvent_BuySignal); ok {
		return x.BuySignal
	}
	return nil
}

func (m *EngineEvent) GetSellSignal() *SellSignal {
	if x, ok := m.GetPayload().(*EngineEvent_SellSignal); ok {
		return x.SellSignal
	}
	return nil
}

func (m *EngineEvent) GetTradeUpdate() *TradeUpdate {
	if x, ok := m.GetPayload().(*EngineEvent_TradeUpdate); ok {
		return x.TradeUpdate
	}
	return nil
}

func (m *EngineEvent) GetPositionUpdate() *PositionUpdate {
	if x, ok := m.GetPayload().(*EngineEvent_PositionUpdate); ok {
		return x.PositionUpdate
	}
	return nil
}

func (m *EngineEvent) GetLog() *LogMessage {
	if x, ok := m.GetPayload().(*EngineEvent_Log); ok {
		return x.Log
	}
	return nil
}

type isEngineEvent_Payload interface {
	isEngineEvent_Payload()
}

type EngineEvent_TokenDetected struct {
	TokenDetected *TokenDetected `protobuf:"bytes,1,opt,name=token_detected,json=tokenDetected,proto3,oneof"`
}
type EngineEvent_TokenFiltered struct {
	TokenFiltered *TokenFiltered `protobuf:"bytes,2,opt,name=token_filtered,json=tokenFiltered,proto3,oneof"`
}
type EngineEvent_BuySignal struct {
	BuySignal *BuySignal `protobuf:"bytes,3,opt,name=buy_signal,json=buySignal,proto3,oneof"`
}
type EngineEvent_SellSignal struct {
	SellSignal *SellSignal `protobuf:"bytes,4,opt,name=sell_signal,json=sellSignal,proto3,oneof"`
}
type EngineEvent_TradeUpdate struct {
	TradeUpdate *TradeUpdate `protobuf:"bytes,5,opt,name=trade_update,json=tradeUpdate,proto3,oneof"`
}
type EngineEvent_PositionUpdate struct {
	PositionUpdate *PositionUpdate `protobuf:"bytes,6,opt,name=position_update,json=positionUpdate,proto3,oneof"`
}
type EngineEvent_Log struct {
	Log *LogMessage `protobuf:"bytes,7,opt,name=log,proto3,oneof"`
}

func (*EngineEvent_TokenDetected) isEngineEvent_Payload()  {}
func (*EngineEvent_TokenFiltered) isEngineEvent_Payload()  {}
func (*EngineEvent_BuySignal) isEngineEvent_Payload()      {}
func (*EngineEvent_SellSignal) isEngineEvent_Payload()     {}
func (*EngineEvent_TradeUpdate) isEngineEvent_Payload()    {}
func (*EngineEvent_PositionUpdate) isEngineEvent_Payload() {}
func (*EngineEvent_Log) isEngineEvent_Payload()            {}

type TokenDetected struct {
	ID                     string  `protobuf:"bytes,1,opt,name=id,proto3"`
	Chain                  string  `protobuf:"bytes,2,opt,name=chain,proto3"`
	Address                string  `protobuf:"bytes,3,opt,name=address,proto3"`
	Symbol                 string  `protobuf:"bytes,4,opt,name=symbol,proto3"`
	Name                   string  `protobuf:"bytes,5,opt,name=name,proto3"`
	LiquidityUsd           float64 `protobuf:"fixed64,6,opt,name=liquidity_usd,json=liquidityUsd,proto3"`
	Holders                int32   `protobuf:"varint,7,opt,name=holders,proto3"`
	AgeSeconds             int32   `protobuf:"varint,8,opt,name=age_seconds,json=ageSeconds,proto3"`
	Top10Pct               float64 `protobuf:"fixed64,9,opt,name=top10_pct,json=top10Pct,proto3"`
	RugScore               float64 `protobuf:"fixed64,10,opt,name=rug_score,json=rugScore,proto3"`
	VolumeUsd              float64 `protobuf:"fixed64,11,opt,name=volume_usd,json=volumeUsd,proto3"`
	PriceUsd               float64 `protobuf:"fixed64,12,opt,name=price_usd,json=priceUsd,proto3"`
	FilterPassed           bool    `protobuf:"varint,13,opt,name=filter_passed,json=filterPassed,proto3"`
	FailReasons            []string `protobuf:"bytes,14,rep,name=fail_reasons,json=failReasons,proto3"`
	DetectedAt             string  `protobuf:"bytes,15,opt,name=detected_at,json=detectedAt,proto3"`
	PoolAddress            string  `protobuf:"bytes,16,opt,name=pool_address,json=poolAddress,proto3"`
	MintAuthorityRevoked   bool    `protobuf:"varint,17,opt,name=mint_authority_revoked,json=mintAuthorityRevoked,proto3"`
	FreezeAuthorityRevoked bool    `protobuf:"varint,18,opt,name=freeze_authority_revoked,json=freezeAuthorityRevoked,proto3"`
	Honeypot               bool    `protobuf:"varint,19,opt,name=honeypot,proto3"`
	BuyTaxPct              float64 `protobuf:"fixed64,20,opt,name=buy_tax_pct,json=buyTaxPct,proto3"`
	SellTaxPct             float64 `protobuf:"fixed64,21,opt,name=sell_tax_pct,json=sellTaxPct,proto3"`
}

func (m *TokenDetected) Reset()         { *m = TokenDetected{} }
func (m *TokenDetected) String() string { return proto.CompactTextString(m) }
func (*TokenDetected) ProtoMessage()    {}

type TokenFiltered struct {
	TokenID              string   `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3"`
	Passed               bool     `protobuf:"varint,2,opt,name=passed,proto3"`
	Reasons              []string `protobuf:"bytes,3,rep,name=reasons,proto3"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenFiltered) Reset()         { *m = TokenFiltered{} }
func (m *TokenFiltered) String() string { return proto.CompactTextString(m) }
func (*TokenFiltered) ProtoMessage()    {}

type BuySignal struct {
	TokenID              string  `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3"`
	Chain                string  `protobuf:"bytes,2,opt,name=chain,proto3"`
	TokenAddress         string  `protobuf:"bytes,3,opt,name=token_address,json=tokenAddress,proto3"`
	TokenSymbol          string  `protobuf:"bytes,4,opt,name=token_symbol,json=tokenSymbol,proto3"`
	AmountUsd            float64 `protobuf:"fixed64,5,opt,name=amount_usd,json=amountUsd,proto3"`
	SlippagePct          float64 `protobuf:"fixed64,6,opt,name=slippage_pct,json=slippagePct,proto3"`
	JitoTipLamports      int64   `protobuf:"varint,7,opt,name=jito_tip_lamports,json=jitoTipLamports,proto3"`
}

func (m *BuySignal) Reset()         { *m = BuySignal{} }
func (m *BuySignal) String() string { return proto.CompactTextString(m) }
func (*BuySignal) ProtoMessage()    {}

type SellSignal struct {
	PositionID           string  `protobuf:"bytes,1,opt,name=position_id,json=positionId,proto3"`
	TokenID              string  `protobuf:"bytes,2,opt,name=token_id,json=tokenId,proto3"`
	Reason               string  `protobuf:"bytes,3,opt,name=reason,proto3"`
	SellPct              float64 `protobuf:"fixed64,4,opt,name=sell_pct,json=sellPct,proto3"`
	TargetPriceUsd       float64 `protobuf:"fixed64,5,opt,name=target_price_usd,json=targetPriceUsd,proto3"`
}

func (m *SellSignal) Reset()         { *m = SellSignal{} }
func (m *SellSignal) String() string { return proto.CompactTextString(m) }
func (*SellSignal) ProtoMessage()    {}

type TradeUpdate struct {
	ID                   string  `protobuf:"bytes,1,opt,name=id,proto3"`
	TokenID              string  `protobuf:"bytes,2,opt,name=token_id,json=tokenId,proto3"`
	TokenSymbol          string  `protobuf:"bytes,3,opt,name=token_symbol,json=tokenSymbol,proto3"`
	Chain                string  `protobuf:"bytes,4,opt,name=chain,proto3"`
	Side                 string  `protobuf:"bytes,5,opt,name=side,proto3"`
	AmountUsd            float64 `protobuf:"fixed64,6,opt,name=amount_usd,json=amountUsd,proto3"`
	PriceUsd             float64 `protobuf:"fixed64,7,opt,name=price_usd,json=priceUsd,proto3"`
	TxHash               string  `protobuf:"bytes,8,opt,name=tx_hash,json=txHash,proto3"`
	Status               string  `protobuf:"bytes,9,opt,name=status,proto3"`
	FeesUsd              float64 `protobuf:"fixed64,10,opt,name=fees_usd,json=feesUsd,proto3"`
	PnlUsd               float64 `protobuf:"fixed64,11,opt,name=pnl_usd,json=pnlUsd,proto3"`
	PnlPct               float64 `protobuf:"fixed64,12,opt,name=pnl_pct,json=pnlPct,proto3"`
	ExecutedAt           string  `protobuf:"bytes,13,opt,name=executed_at,json=executedAt,proto3"`
	SellReason           string  `protobuf:"bytes,14,opt,name=sell_reason,json=sellReason,proto3"`
}

func (m *TradeUpdate) Reset()         { *m = TradeUpdate{} }
func (m *TradeUpdate) String() string { return proto.CompactTextString(m) }
func (*TradeUpdate) ProtoMessage()    {}

type PositionUpdate struct {
	ID                   string  `protobuf:"bytes,1,opt,name=id,proto3"`
	TokenID              string  `protobuf:"bytes,2,opt,name=token_id,json=tokenId,proto3"`
	TokenSymbol          string  `protobuf:"bytes,3,opt,name=token_symbol,json=tokenSymbol,proto3"`
	Chain                string  `protobuf:"bytes,4,opt,name=chain,proto3"`
	EntryPriceUsd        float64 `protobuf:"fixed64,5,opt,name=entry_price_usd,json=entryPriceUsd,proto3"`
	CurrentPriceUsd      float64 `protobuf:"fixed64,6,opt,name=current_price_usd,json=currentPriceUsd,proto3"`
	PeakPriceUsd         float64 `protobuf:"fixed64,7,opt,name=peak_price_usd,json=peakPriceUsd,proto3"`
	SizeUsd              float64 `protobuf:"fixed64,8,opt,name=size_usd,json=sizeUsd,proto3"`
	Status               string  `protobuf:"bytes,9,opt,name=status,proto3"`
	Tp1Hit               bool    `protobuf:"varint,10,opt,name=tp1_hit,json=tp1Hit,proto3"`
	TrailingStopActive   bool    `protobuf:"varint,11,opt,name=trailing_stop_active,json=trailingStopActive,proto3"`
	StopLossPrice        float64 `protobuf:"fixed64,12,opt,name=stop_loss_price,json=stopLossPrice,proto3"`
	UnrealisedPnlUsd     float64 `protobuf:"fixed64,13,opt,name=unrealised_pnl_usd,json=unrealisedPnlUsd,proto3"`
	UnrealisedPnlPct     float64 `protobuf:"fixed64,14,opt,name=unrealised_pnl_pct,json=unrealisedPnlPct,proto3"`
	OpenedAt             string  `protobuf:"bytes,15,opt,name=opened_at,json=openedAt,proto3"`
	ClosedAt             string  `protobuf:"bytes,16,opt,name=closed_at,json=closedAt,proto3"`
}

func (m *PositionUpdate) Reset()         { *m = PositionUpdate{} }
func (m *PositionUpdate) String() string { return proto.CompactTextString(m) }
func (*PositionUpdate) ProtoMessage()    {}

type LogMessage struct {
	Level                string  `protobuf:"bytes,1,opt,name=level,proto3"`
	Message              string  `protobuf:"bytes,2,opt,name=message,proto3"`
	Timestamp            string  `protobuf:"bytes,3,opt,name=timestamp,proto3"`
}

func (m *LogMessage) Reset()         { *m = LogMessage{} }
func (m *LogMessage) String() string { return proto.CompactTextString(m) }
func (*LogMessage) ProtoMessage()    {}

func init() {
	proto.RegisterEnum("engine.ControlCommand_Action", ControlCommand_Action_name, ControlCommand_Action_value)
	proto.RegisterType((*EngineCommand)(nil), "engine.EngineCommand")
	proto.RegisterType((*ControlCommand)(nil), "engine.ControlCommand")
	proto.RegisterType((*BotConfig)(nil), "engine.BotConfig")
	proto.RegisterType((*EngineEvent)(nil), "engine.EngineEvent")
	proto.RegisterType((*TokenDetected)(nil), "engine.TokenDetected")
	proto.RegisterType((*TokenFiltered)(nil), "engine.TokenFiltered")
	proto.RegisterType((*BuySignal)(nil), "engine.BuySignal")
	proto.RegisterType((*SellSignal)(nil), "engine.SellSignal")
	proto.RegisterType((*TradeUpdate)(nil), "engine.TradeUpdate")
	proto.RegisterType((*PositionUpdate)(nil), "engine.PositionUpdate")
	proto.RegisterType((*LogMessage)(nil), "engine.LogMessage")
}

var fileDescriptor_engine = []byte{
	0x0a, 0x0b, 0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
}
